name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '21.4' # Set this to the Node.js version you use

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build
